In [5]:
!pip install pandas



[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [12]:
import numpy as np  # optional
import pandas as pd
print(pd.__version__)
print(pd.show_versions(as_json=True))


3.0.1
{
  "system": {
    "commit": "e04b26f375035e5106cb913e47b6db612f4ebb11",
    "python": "3.14.3",
    "python-bits": 64,
    "OS": "Windows",
    "OS-release": "10",
    "Version": "10.0.19045",
    "machine": "AMD64",
    "processor": "Intel64 Family 6 Model 142 Stepping 12, GenuineIntel",
    "byteorder": "little",
    "LC_ALL": null,
    "LANG": null,
    "LOCALE": {
      "language-code": "English_United States",
      "encoding": "1252"
    }
  },
  "dependencies": {
    "pandas": "3.0.1",
    "numpy": "2.4.2",
    "dateutil": "2.9.0.post0",
    "pip": "25.3",
    "Cython": null,
    "sphinx": null,
    "IPython": "9.10.0",
    "adbc-driver-postgresql": null,
    "adbc-driver-sqlite": null,
    "bs4": "4.14.3",
    "bottleneck": null,
    "fastparquet": null,
    "fsspec": null,
    "html5lib": null,
    "hypothesis": null,
    "gcsfs": null,
    "jinja2": "3.1.6",
    "lxml.etree": null,
    "matplotlib": null,
    "numba": null,
    "numexpr": null,
    "odfpy": null,
    

In [7]:
import numpy as np
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))

ser1 = pd.Series(mylist)
ser2 = pd.Series(myarr)
ser3 = pd.Series(mydict)
print(ser3.head())


a    0
b    1
c    2
e    3
d    4
dtype: int32


In [9]:
mylist = list('abcedfghijklmnopqrstuvwxyz')
myarr = np.arange(26)
mydict = dict(zip(mylist, myarr))
ser = pd.Series(mydict)

df = ser.to_frame().reset_index()
print(df.head())


  index  0
0     a  0
1     b  1
2     c  2
3     e  3
4     d  4


In [11]:
import numpy as np
ser1 = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
ser2 = pd.Series(np.arange(26))

df = pd.concat([ser1, ser2], axis=1)

df = pd.DataFrame({'col1': ser1, 'col2': ser2})
print(df.head())


  col1  col2
0    a     0
1    b     1
2    c     2
3    e     3
4    d     4


In [13]:
ser = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))

ser.name = 'alphabets'
ser.head()


0    a
1    b
2    c
3    e
4    d
Name: alphabets, dtype: object

In [15]:
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

ser1[~ser1.isin(ser2)]


0    1
1    2
2    3
dtype: int64

In [17]:
ser1 = pd.Series([1, 2, 3, 4, 5])
ser2 = pd.Series([4, 5, 6, 7, 8])

ser_u = pd.Series(np.union1d(ser1, ser2))  # union
ser_i = pd.Series(np.intersect1d(ser1, ser2))  # intersect
ser_u[~ser_u.isin(ser_i)]

0    1
1    2
2    3
5    6
6    7
7    8
dtype: int64

In [19]:
state = np.random.RandomState(100)
ser = pd.Series(state.normal(10, 5, 25))

np.percentile(ser, q=[0, 25, 50, 75, 100])


array([ 1.25117263,  7.70986507, 10.92259345, 13.36360403, 18.0949083 ])

In [21]:
ser = pd.Series(np.take(list('abcdefgh'), np.random.randint(8, size=30)))

ser.value_counts()

c    7
f    6
g    5
h    4
b    2
e    2
a    2
d    2
Name: count, dtype: int64

In [37]:
rng = np.random.RandomState(100)
ser = pd.Series(rng.randint(1, 5, 12))

top2 = ser.value_counts().nlargest(2).index
print("Top 2 Freq:", top2.tolist())

ser[~ser.isin(top2)] = 'Other'
print(ser)

Top 2 Freq: [1, 4]
0         1
1         1
2         4
3         4
4         4
5         4
6         1
7     Other
8     Other
9         1
10    Other
11    Other
dtype: object


C:\Users\CICT\AppData\Local\Temp\ipykernel_4292\2168830007.py:7: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Other' has dtype incompatible with int32, please explicitly cast to a compatible dtype first.
  ser[~ser.isin(top2)] = 'Other'


In [41]:
ser = pd.Series(np.random.random(20))
print(ser.head())

pd.qcut(ser, q=[0, .10, .20, .3, .4, .5, .6, .7, .8, .9, 1], 
        labels=['1st', '2nd', '3rd', '4th', '5th', '6th', '7th', '8th', '9th', '10th']).head()


0    0.544901
1    0.099272
2    0.004159
3    0.311281
4    0.206849
dtype: float64


0    6th
1    2nd
2    1st
3    4th
4    3rd
dtype: category
Categories (10, object): ['1st' < '2nd' < '3rd' < '4th' ... '7th' < '8th' < '9th' < '10th']

In [73]:
ser = pd.Series(np.random.randint(1, 10, 35))

df = pd.DataFrame(ser.values.reshape(7,5))
print(df)

   0  1  2  3  4
0  4  1  5  5  9
1  4  1  4  3  1
2  5  2  7  9  6
3  3  9  6  2  6
4  6  9  1  3  7
5  7  9  9  9  2
6  9  3  2  8  9


In [75]:
ser = pd.Series(np.random.randint(1, 10, 7))
ser

print(ser)
np.argwhere(ser % 3==0)

0    2
1    4
2    7
3    2
4    7
5    1
6    2
dtype: int32


array([], shape=(0, 1), dtype=int64)

In [77]:
ser = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
pos = [0, 4, 8, 14, 20]

ser.take(pos)

0     a
4     e
8     i
14    o
20    u
dtype: object

In [91]:
ser1 = pd.Series(range(5))
ser2 = pd.Series(list('abcde'))

# Vertical
#ser1.append(ser2)
v = pd.concat([ser1, ser2], axis=0, ignore_index=True)
print(v)

# Horizontal
df = pd.concat([ser1, ser2], axis=1)
print(df)


0    0
1    1
2    2
3    3
4    4
5    a
6    b
7    c
8    d
9    e
dtype: object
   0  1
0  0  a
1  1  b
2  2  c
3  3  d
4  4  e


In [93]:
ser1 = pd.Series([10, 9, 6, 5, 3, 1, 12, 8, 13])
ser2 = pd.Series([1, 3, 10, 13])

# Solution 1
[np.where(i == ser1)[0].tolist()[0] for i in ser2]

# Solution 2
[pd.Index(ser1).get_loc(i) for i in ser2]


[5, 4, 0, 8]

In [95]:
truth = pd.Series(range(10))
pred = pd.Series(range(10)) + np.random.random(10)

np.mean((truth-pred)**2)


0.28313862231617504

In [87]:
ser = pd.Series(['how', 'to', 'kick', 'ass?'])

# Solution 1
ser.map(lambda x: x.title())

# Solution 2
ser.map(lambda x: x[0].upper() + x[1:])

# Solution 3
pd.Series([i.title() for i in ser])


0     How
1      To
2    Kick
3    Ass?
dtype: object

In [79]:
ser = pd.Series(['how', 'to', 'kick', 'ass?'])

ser.map(lambda x: len(x))


0    3
1    2
2    4
3    4
dtype: int64

In [83]:
ser = pd.Series([1, 3, 6, 10, 15, 21, 27, 35])

print(ser.diff().tolist())
print(ser.diff().diff().tolist())

[nan, 2.0, 3.0, 4.0, 5.0, 6.0, 6.0, 8.0]
[nan, nan, 1.0, 1.0, 1.0, 1.0, 0.0, 2.0]


In [137]:
import pandas as pd

ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', 
                 '2013/04/04', '2014-05-05', '2015-06-06T12:20'])


result = pd.to_datetime(ser, format='mixed')
print(result)

0   2010-01-01 00:00:00
1   2011-02-02 00:00:00
2   2012-03-03 00:00:00
3   2013-04-04 00:00:00
4   2014-05-05 00:00:00
5   2015-06-06 12:20:00
dtype: datetime64[ns]


In [139]:
import pandas as pd
from dateutil.parser import parse

ser = pd.Series(['01 Jan 2010', '02-02-2011', '20120303', '2013/04/04', '2014-05-05', '2015-06-06T12:20'])

ser_ts = ser.map(lambda x: parse(x))

# day of month
print("Date: ", ser_ts.dt.day.tolist())

# week number
print("Week number: ", ser_ts.dt.isocalendar().week.tolist())

# day of year
print("Day number of year: ", ser_ts.dt.dayofyear.tolist())

# day of week
print("Day of week: ", ser_ts.dt.day_name().tolist())

Date:  [1, 2, 3, 4, 5, 6]
Week number:  [53, 5, 9, 14, 19, 23]
Day number of year:  [1, 33, 63, 94, 125, 157]
Day of week:  ['Friday', 'Wednesday', 'Saturday', 'Thursday', 'Monday', 'Saturday']


In [141]:
import pandas as pd
ser = pd.Series(['Jan 2010', 'Feb 2011', 'Mar 2012'])

# Solution 1
from dateutil.parser import parse
ser_ts = ser.map(lambda x: parse(x))
ser_datestr = ser_ts.dt.year.astype('str') + '-' + ser_ts.dt.month.astype('str') + '-' + '04'
[parse(i).strftime('%Y-%m-%d') for i in ser_datestr]

# Solution 2
ser.map(lambda x: parse('04 ' + x))


0   2010-01-04
1   2011-02-04
2   2012-03-04
dtype: datetime64[ns]

In [143]:
ser = pd.Series(['Apple', 'Orange', 'Plan', 'Python', 'Money'])

from collections import Counter
mask = ser.map(lambda x: sum([Counter(x.lower()).get(i, 0) for i in list('aeiou')]) >= 2)
ser[mask]


0     Apple
1    Orange
4     Money
dtype: object

In [147]:
emails = pd.Series(['buying books at amazom.com', 'rameses@egypt.com', 'matt@t.co', 'narendra@modi.com'])

# Solution 1 (as series of strings)
import re
pattern ='[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,4}'
mask = emails.map(lambda x: bool(re.match(pattern, x)))
emails[mask]

# Solution 2 (as series of list)
emails.str.findall(pattern, flags=re.IGNORECASE)

# Solution 3 (as list)
[x[0] for x in [re.findall(pattern, email) for email in emails] if len(x) > 0]


['rameses@egypt.com', 'matt@t.co', 'narendra@modi.com']

In [169]:
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))

weights.groupby(fruit).mean()


apple     4.000000
banana    7.333333
carrot    6.500000
dtype: float64

In [173]:
p = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
q = pd.Series([10, 9, 8, 7, 6, 5, 4, 3, 2, 1])

sum((p - q)**2)**.5

# Solution (using func)
np.linalg.norm(p-q)


18.16590212458495

In [177]:
ser = pd.Series([2, 10, 3, 4, 9, 10, 2, 7, 3])

dd = np.diff(np.sign(np.diff(ser)))
peak_locs = np.where(dd == -2)[0] + 1
peak_locs


array([1, 5, 7], dtype=int64)

In [181]:
my_str = 'dbc deb abed gade'

ser = pd.Series(list('dbc deb abed gade'))
freq = ser.value_counts()
print(freq)
least_freq = freq.dropna().index[-1]
"".join(ser.replace(' ', least_freq))


d    4
b    3
     3
e    3
a    2
c    1
g    1
Name: count, dtype: int64


'dbcgdebgabedggade'

In [185]:
ser = pd.Series(np.random.randint(1,10,10), pd.date_range('2000-01-01', periods=10, freq='W-SAT'))
ser


2000-01-01    3
2000-01-08    4
2000-01-15    4
2000-01-22    6
2000-01-29    3
2000-02-05    2
2000-02-12    7
2000-02-19    4
2000-02-26    4
2000-03-04    7
Freq: W-SAT, dtype: int32

In [189]:
ser = pd.Series([1,10,3, np.nan], index=pd.to_datetime(['2000-01-01', '2000-01-03', '2000-01-06', '2000-01-08']))

ser.resample('D').ffill()  # fill with previous value

ser.resample('D').bfill()  # fill with next value
ser.resample('D').bfill().ffill()  # fill next else prev value


2000-01-01     1.0
2000-01-02    10.0
2000-01-03    10.0
2000-01-04     3.0
2000-01-05     3.0
2000-01-06     3.0
2000-01-07     3.0
2000-01-08     3.0
Freq: D, dtype: float64

In [191]:
ser = pd.Series(np.arange(20) + np.random.normal(1, 10, 20))

autocorrelations = [ser.autocorr(i).round(2) for i in range(11)]
print(autocorrelations[1:])
print('Lag having highest correlation: ', np.argmax(np.abs(autocorrelations[1:]))+1)


[-0.35, -0.17, 0.5, -0.23, -0.1, 0.06, 0.34, 0.06, -0.28, 0.28]
Lag having highest correlation:  3


In [199]:
df_chunks = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv', chunksize=50)
first_rows = []
for chunk in df_chunks:
    first_rows.append(chunk.iloc[0])

# Tạo DataFrame từ list
df2 = pd.DataFrame(first_rows)
print(df2.head())

        crim    zn  indus  chas    nox     rm   age     dis  rad    tax  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
50   0.08873  21.0   5.64   0.0  0.439  5.963  45.7  6.8147  4.0  243.0   
100  0.14866   0.0   8.56   0.0  0.520  6.727  79.9  2.7778  5.0  384.0   
150  1.65660   0.0  19.58   0.0  0.871  6.122  97.3  1.6180  5.0  403.0   
200  0.01778  95.0   1.47   0.0  0.403  7.135  13.9  7.6534  3.0  402.0   

     ptratio       b  lstat  medv  
0       15.3  396.90   4.98  24.0  
50      16.8  395.56  13.45  19.7  
100     20.9  394.76   9.42  27.5  
150     14.7  372.80  14.10  21.5  
200     17.0  384.30   4.45  32.9  


In [205]:
L = pd.Series(range(15))

def gen_strides(a, stride_len=5, window_len=5):
    n_strides = ((a.size-window_len)//stride_len) + 1
    return np.array([a[s:(s+window_len)] for s in np.arange(0, a.size, stride_len)[:n_strides]])

gen_strides(L, stride_len=2, window_len=4)


array([[ 0,  1,  2,  3],
       [ 2,  3,  4,  5],
       [ 4,  5,  6,  7],
       [ 6,  7,  8,  9],
       [ 8,  9, 10, 11],
       [10, 11, 12, 13]], dtype=int64)

In [207]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv', usecols=['crim', 'medv'])
print(df.head())

      crim  medv
0  0.00632  24.0
1  0.02731  21.6
2  0.02729  34.7
3  0.03237  33.4
4  0.06905  36.2


In [211]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
print(df.shape)

# datatypes
print(df.dtypes)

# how many columns under each dtype
print(df.get_dtype_counts())
print(df.dtypes.value_counts())

# summary statistics
df_stats = df.describe()

# numpy array 
df_arr = df.values

# list
df_list = df.values.tolist()


(93, 27)
Manufacturer           object
Model                  object
Type                   object
Min.Price             float64
Price                 float64
Max.Price             float64
MPG.city              float64
MPG.highway           float64
AirBags                object
DriveTrain             object
Cylinders              object
EngineSize            float64
Horsepower            float64
RPM                   float64
Rev.per.mile          float64
Man.trans.avail        object
Fuel.tank.capacity    float64
Passengers            float64
Length                float64
Wheelbase             float64
Width                 float64
Turn.circle           float64
Rear.seat.room        float64
Luggage.room          float64
Weight                float64
Origin                 object
Make                   object
dtype: object


AttributeError: 'DataFrame' object has no attribute 'get_dtype_counts'

In [217]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

# Step 1:
df=df.rename(columns = {'Type':'CarType'})
# or
df.columns.values[2] = "CarType"

# Step 2:
df.columns = df.columns.map(lambda x: x.replace('.', '_'))
print(df.columns)

Index(['Manufacturer', 'Model', 'CarType', 'Min_Price', 'Price', 'Max_Price',
       'MPG_city', 'MPG_highway', 'AirBags', 'DriveTrain', 'Cylinders',
       'EngineSize', 'Horsepower', 'RPM', 'Rev_per_mile', 'Man_trans_avail',
       'Fuel_tank_capacity', 'Passengers', 'Length', 'Wheelbase', 'Width',
       'Turn_circle', 'Rear_seat_room', 'Luggage_room', 'Weight', 'Origin',
       'Make'],
      dtype='object')


In [225]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
df.isnull().values.any()


True

In [8]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

n_missings_each_col = df.apply(lambda x: x.isnull().sum())
n_missings_each_col.argmax()

np.int64(8)

In [15]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

df_out = df[['Min.Price', 'Max.Price']] = df[['Min.Price', 'Max.Price']].apply(lambda x: x.fillna(x.mean()))
print(df_out.head())


   Min.Price  Max.Price
0  12.900000  18.800000
1  29.200000  38.700000
2  25.900000  32.300000
3  17.118605  44.600000
4  17.118605  21.459091


In [18]:
df = pd.DataFrame(np.arange(20).reshape(-1, 5), columns=list('abcde'))

type(df[['a']])
type(df.loc[:, ['a']])
type(df.iloc[:, [0]])

type(df.a)
type(df['a'])
type(df.loc[:, 'a'])
type(df.iloc[:, 1])


pandas.Series

In [24]:
# Input
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

# Solution
pd.set_option('display.max_columns', 10)
pd.set_option('display.max_rows', 10)
#df

# Show all available options
#pd.describe_option()


In [27]:
df = pd.DataFrame(np.random.random(4), columns=['random'])

out = df.style.format({
    'random': '{0:.2%}'.format,
})

out


,random
0,50.95%
1,64.42%
2,69.22%
3,63.24%


In [29]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

print(df.iloc[::20, :][['Manufacturer', 'Model', 'Type']])


   Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small


In [33]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv', usecols=[0,1,2,3,5])

df[['Manufacturer', 'Model', 'Type']] = df[['Manufacturer', 'Model', 'Type']].fillna('missing')
df.index = df.Manufacturer + '_' + df.Model + '_' + df.Type
print(df.index.is_unique)

True


In [40]:
ser = pd.Series(np.random.randint(1, 100, 15))

print('ser: ', ser.tolist(), 'mean: ', round(ser.mean()))
np.argwhere(ser > ser.mean())[1]

ser:  [9, 42, 34, 86, 89, 41, 76, 87, 32, 57, 95, 65, 12, 64, 92] mean:  59


array([4])

In [43]:
ser = pd.Series(np.logspace(-2, 2, 30))

def cap_outliers(ser, low_perc, high_perc):
    low, high = ser.quantile([low_perc, high_perc])
    print(low_perc, '%ile: ', low, '|', high_perc, '%ile: ', high)
    ser[ser < low] = low
    ser[ser > high] = high
    return(ser)

capped_ser = cap_outliers(ser, .05, .95)

0.05 %ile:  0.016049294076965887 | 0.95 %ile:  63.87667222018393


In [44]:
df = pd.DataFrame(np.arange(25).reshape(5, -1))

def swap_rows(df, i1, i2):
    a, b = df.iloc[i1, :].copy(), df.iloc[i2, :].copy()
    df.iloc[i1, :], df.iloc[i2, :] = b, a
    return df

print(swap_rows(df, 1, 2))

    0   1   2   3   4
0   0   1   2   3   4
1  10  11  12  13  14
2   5   6   7   8   9
3  15  16  17  18  19
4  20  21  22  23  24


In [47]:
df = pd.DataFrame(np.arange(25).reshape(5, -1))

# Solution 1
df.iloc[::-1, :]

# Solution 2
print(df.loc[df.index[::-1], :])


    0   1   2   3   4
4  20  21  22  23  24
3  15  16  17  18  19
2  10  11  12  13  14
1   5   6   7   8   9
0   0   1   2   3   4


In [49]:
# Input
df = pd.DataFrame(np.arange(25).reshape(5,-1), columns=list('abcde'))

# Solution
df_onehot = pd.concat([pd.get_dummies(df['a']), df[list('bcde')]], axis=1)
print(df_onehot)

       0      5     10     15     20   b   c   d   e
0   True  False  False  False  False   1   2   3   4
1  False   True  False  False  False   6   7   8   9
2  False  False   True  False  False  11  12  13  14
3  False  False  False   True  False  16  17  18  19
4  False  False  False  False   True  21  22  23  24


In [51]:
df = pd.DataFrame(np.random.randint(1,100, 40).reshape(10, -1))

print('Column with highest row maxes: ', df.apply(np.argmax, axis=1).value_counts().index[0])


Column with highest row maxes:  2


In [53]:
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1), columns=list('pqrstuvwxy'), index=list('abcdefgh'))
df

abs_corrmat = np.abs(df.corr())
max_corr = abs_corrmat.apply(lambda x: sorted(x)[-2])
print('Maximum Correlation possible for each column: ', np.round(max_corr.tolist(), 2))

Maximum Correlation possible for each column:  [0.69 0.73 0.73 0.52 0.63 0.77 0.77 0.68 0.65 0.65]


In [55]:
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))

out = df.apply(lambda x: x.sort_values().unique()[-2], axis=1)
df['penultimate'] = out
print(df)


    0   1   2   3   4  ...   6   7   8   9  penultimate
0  94   7  73  94  96  ...  38  19  47  54           94
1  86  52  76  74  46  ...  38  45  40  46           76
2  88   9  69  19  96  ...  81  47  80  21           88
3  73  88  86  26   5  ...   5   2  15   6           88
4   7  97  27  69  43  ...  36  73  65  72           73
5   5  74  98  20  12  ...   8  84  50  35           84
6  11  79  43  13  75  ...  27  32  62  35           75
7  45  45  39  13  53  ...  49  49  95  94           94

[8 rows x 11 columns]


In [56]:
df = pd.DataFrame(np.random.randint(1,100, 80).reshape(8, -1))

# Solution Q1
out1 = df.apply(lambda x: ((x - x.mean())/x.std()).round(2))
print('Solution Q1\n',out1)

# Solution Q2
out2 = df.apply(lambda x: ((x.max() - x)/(x.max() - x.min())).round(2))
print('Solution Q2\n', out2)  

Solution Q1
       0     1     2     3     4     5     6     7     8     9
0 -0.88  1.11  0.16 -1.34 -0.50  0.47 -0.84 -1.37 -0.60  0.31
1 -0.43 -0.70  0.08 -0.51  0.37  1.10  0.66 -0.46 -0.60  0.65
2 -0.48  0.65  0.50  0.25 -0.46 -0.92  0.80  1.42  1.21 -0.89
3  0.92  0.62 -0.05  0.00 -0.65  1.23 -0.71 -0.56  1.38  1.34
4  1.40 -1.46  0.42  1.02 -0.76 -0.98  1.50 -0.06  0.46 -0.33
5 -0.78  1.11 -1.60  0.94  1.41  0.82 -1.55 -0.87  0.18 -0.37
6 -0.96 -0.34  1.63  1.02 -0.98 -1.08  0.22  0.95 -1.56  0.95
7  1.22 -1.00 -1.14 -1.38  1.56 -0.64 -0.09  0.95 -0.46 -1.66
Solution Q2
       0     1     2     3     4     5     6     7     8     9
0  0.97  0.00  0.45  0.98  0.81  0.33  0.77  1.00  0.67  0.34
1  0.77  0.71  0.48  0.64  0.47  0.05  0.28  0.67  0.67  0.23
2  0.80  0.18  0.35  0.32  0.79  0.93  0.23  0.00  0.06  0.74
3  0.20  0.19  0.52  0.42  0.87  0.00  0.72  0.71  0.00  0.00
4  0.00  1.00  0.38  0.00  0.91  0.96  0.00  0.53  0.31  0.56
5  0.92  0.00  1.00  0.03  0.06  0.18  1.00 

In [64]:
df = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                   'taste': np.random.rand(9),
                   'price': np.random.randint(0, 15, 9)})

print(df)

# Solution
df_grpd = df['taste'].groupby(df.fruit)
df_grpd.get_group('banana').sort_values().iloc[-2]


    fruit     taste  price
0   apple  0.182096      5
1  banana  0.395327      5
2  orange  0.405354      4
3   apple  0.554740     12
4  banana  0.050961     14
5  orange  0.728499     10
6   apple  0.464288     14
7  banana  0.263960     14
8  orange  0.801695      9


np.float64(0.2639598779234068)

In [65]:
df = pd.DataFrame({'fruit': ['apple', 'banana', 'orange'] * 3,
                   'rating': np.random.rand(9),
                   'price': np.random.randint(0, 15, 9)})

out = df.groupby('fruit', as_index=False)['price'].mean()
print(out)


    fruit      price
0   apple  10.000000
1  banana   4.333333
2  orange   7.000000


In [68]:
df1 = pd.DataFrame({'fruit': ['apple', 'orange', 'banana'] * 3,
                    'weight': ['high', 'medium', 'low'] * 3,
                    'price': np.arange(9)})

df2 = pd.DataFrame({'fruit': ['apple', 'orange', 'pine'] * 2,
                    'weight': ['high', 'medium'] * 3,
                    'price': np.arange(6)})

print(df1[~df1.isin(df2).all(1)])

    fruit  weight  price
2  banana     low      2
3   apple    high      3
4  orange  medium      4
5  banana     low      5
6   apple    high      6
7  orange  medium      7
8  banana     low      8


C:\Users\Admin\AppData\Local\Temp\ipykernel_88\762096016.py:9: Pandas4Warning: Starting with pandas version 4.0 all arguments of all will be keyword-only.
  print(df1[~df1.isin(df2).all(1)])


In [69]:
df = pd.DataFrame({'fruit1': np.random.choice(['apple', 'orange', 'banana'], 10),
                    'fruit2': np.random.choice(['apple', 'orange', 'banana'], 10)})

np.where(df.fruit1 == df.fruit2)


(array([1, 4, 6, 9]),)

In [70]:
df = pd.DataFrame(np.random.randint(1, 100, 20).reshape(-1, 4), columns = list('abcd'))

df['a_lag1'] = df['a'].shift(1)
df['b_lead1'] = df['b'].shift(-1)
print(df)


    a   b   c   d  a_lag1  b_lead1
0  83  66  42  50     NaN     88.0
1  46  88  96  54    83.0     51.0
2  31  51   2  65    46.0      6.0
3  47   6  23  62    31.0     23.0
4  24  23  92  93    47.0      NaN


In [73]:
df = pd.DataFrame(["STD, City    State",
"33, Kolkata    West Bengal",
"44, Chennai    Tamil Nadu",
"40, Hyderabad    Telengana",
"80, Bangalore    Karnataka"], columns=['row'])

df_out = df.row.str.split(',|\t', expand=True)

# Make first row as header
new_header = df_out.iloc[0]
df_out = df_out[1:]
df_out.columns = new_header
print(df_out)

0 STD            City    State
1  33   Kolkata    West Bengal
2  44    Chennai    Tamil Nadu
3  40   Hyderabad    Telengana
4  80   Bangalore    Karnataka
